name: Youtube Music - Random track from playlist
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-music:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.svg
          base: ""
          token: NOT_NEEDED
          optimize: svg
          experimental_features: --optimize-svg
          config_display: large
          config_timezone: Asia/Bangkok
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics overview"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          use_prebuilt_image: yes
          plugin_music_token: ${{ secrets.YOUTUBE_KEY }}
          plugin_music: yes
          plugin_music_playlist: >-
            https://music.youtube.com/playlist?list=PLdcv4LvyAC23aWRzCOH4lrCxblGpRCzlF
          